deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    # Demo only: open to all. Narrow CIDR in production.
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30
apisix:
  node_listen: 9080
  enable_admin: true
  ssl:
    enable: true
    listen_port: 9443
  router:
    http: radixtree_uri_with_parameter
stream_plugins: []
plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
nginx_config:
  error_log: logs/error.log
  worker_processes: auto
  worker_rlimit_nofile: 20480
  http:
    access_log: logs/access.log
    keepalive_timeout: 60s
